require("core/keymaps")
require("core/options")
require("core/colorscheme")

require("plugins/packer")
require("plugins/nvim-tree")
require("plugins/theme_vscode")
require("plugins/lualine")
require("plugins/bufferline")
require("plugins/nvim-treesitter")
require("plugins/toggleterm")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/telescope")
require("plugins/hop")
